# Generated by Django 4.2.6 on 2023-10-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('E', 'CAJA DE EFECTIVO'), ('B', 'CUENTA BANCARIA')], max_length=1, verbose_name='Tipo')),
                ('initial', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('R', 'Realizado'), ('A', 'Anulado')], default='R', max_length=1, verbose_name='Estado')),
                ('type', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('A', 'Apertura'), ('C', 'Cierre')], max_length=1, verbose_name='Tipo')),
                ('payment', models.CharField(choices=[('P', 'Pagado'), ('C', 'Credito')], default='P', max_length=1, verbose_name='Pago')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de operacion')),
                ('description', models.CharField(default='-', max_length=250, verbose_name='Descripcion de la operacion')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date_payment', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='E/B')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['id'],
            },
        ),
    ]
